# NumPy Practice

In [1]:
import numpy as np

### Creating basic NumPy arrays

In [2]:
# Creating a 1-dimensional NumPy array
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [3]:
# Creating a 2-dimensional NumPy array
array_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Creating a 3-dimensional NumPy array
array_3d = np.array([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],
                     [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
# Getting the attributes from the 1-dimensional array
array_1d.shape, array_1d.ndim, array_1d.dtype, array_1d.size

((3,), 1, dtype('int64'), 3)

In [6]:
# Getting the attributes from the 2-dimensional array
array_2d.shape, array_2d.ndim, array_2d.dtype, array_2d.size

((2, 3), 2, dtype('int64'), 6)

In [7]:
# Getting the attributes from the 3-dimensional array
array_3d.shape, array_3d.ndim, array_3d.dtype, array_3d.size

((2, 3, 3), 3, dtype('int64'), 18)

### Different ways of creating NumPy arrays

In [8]:
# Using pandas
import pandas as pd
df = pd.DataFrame(array_2d)
df

0  1  2
0  1  2  3
1  4  5  6

In [10]:
# Creating an array, shape (10, 2), using only ones
array_ones = np.ones((10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Creating an array, shape (7, 2, 3), using only zeros
array_zeros = np.zeros((7, 2, 3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Creating an array within a range of 0 and 100
range_array = np.arange(0, 100, 2) # 2 is the step
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
# Creating an array with random numbers between 0 and 10, size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[2, 2],
       [6, 9],
       [2, 2],
       [5, 2],
       [8, 8],
       [4, 7],
       [7, 9]])

In [16]:
# Creating an array with random floats between 0 and 1, shape (3, 5)
np.random.random((3, 5))

array([[0.70281465, 0.69809496, 0.05615899, 0.52905443, 0.86613821],
       [0.86880718, 0.44043958, 0.00965387, 0.8801268 , 0.44457555],
       [0.4970308 , 0.37789324, 0.2030937 , 0.57987694, 0.27892141]])

In [17]:
# Using a random seed
np.random.seed(0) # 0 can be any number

# Creating an array with random numbers between 0 and 10, size (4, 6)
np.random.randint(10, size=(4, 6))

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9]])

In [18]:
# Creating an arrays of random numbers between 1 and 20, size (3, 7)
my_array = np.random.randint(1, 10, size=(3, 7))

# Finding unique numbers
np.unique(my_array)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [19]:
# Getting the first 2 rows from the last array
my_array[:2]

array([[5, 4, 1, 4, 6, 1, 3],
       [4, 9, 2, 4, 4, 4, 8]])

In [20]:
# Getting the first 2 values from the first 2 rows from the last array
my_array[:2, :2]

array([[5, 4],
       [4, 9]])

In [24]:
# Create an array with random numbers between 0 and 10, and an array of ones
random_array_numbers = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [25]:
# Adding the arrays
random_array_numbers + ones

array([[ 4.,  1.,  6.,  1.,  2.],
       [ 3.,  5.,  3.,  1.,  4.],
       [ 3.,  1.,  8.,  6., 10.]])

### Arithmetic operations

In [26]:
# Multiplying arrays
random_array_numbers * ones

array([[3., 0., 5., 0., 1.],
       [2., 4., 2., 0., 3.],
       [2., 0., 7., 5., 9.]])

In [27]:
# Exponentiation
random_array_numbers ** 2

array([[ 9,  0, 25,  0,  1],
       [ 4, 16,  4,  0,  9],
       [ 4,  0, 49, 25, 81]])

In [30]:
# Square roots
np.square(random_array_numbers)

array([[ 9,  0, 25,  0,  1],
       [ 4, 16,  4,  0,  9],
       [ 4,  0, 49, 25, 81]])

In [31]:
# Getting the mean
np.mean(random_array_numbers)

2.8666666666666667

In [32]:
# Getting the maximum
np.max(random_array_numbers)

9

In [33]:
# Getting the minimum
np.min(random_array_numbers)

0

In [34]:
# Getting the std
np.std(random_array_numbers)

2.6297443897754693

In [35]:
# Getting the variance
np.var(random_array_numbers)

6.915555555555555

### Reshaping, Transposing and Dot Product

In [36]:
# Reshaping the last array, shape (3, 5, 1)
random_array_numbers.reshape(3, 5, 1)

array([[[3],
        [0],
        [5],
        [0],
        [1]],

       [[2],
        [4],
        [2],
        [0],
        [3]],

       [[2],
        [0],
        [7],
        [5],
        [9]]])

In [38]:
# Transposing the latest array
random_array_numbers.T

array([[3, 2, 2],
       [0, 4, 0],
       [5, 2, 7],
       [0, 0, 5],
       [1, 3, 9]])

In [39]:
# Creating two arrays with random numbers between 0 and 10
array_1 = np.random.randint(10, size=(3, 3))
array_2 = np.random.randint(10, size=(3, 2))

In [40]:
# Performing a dot product
np.dot(array_1, array_2)

array([[65, 11],
       [33, 28],
       [30, 20]])

Transpose (.T) can help for performing the dot product when both arrays have the same size.

In [42]:
# Creating two arrays with random numbers between 0 and 10, same size
array_3 = np.random.randint(10, size=(3,3))
array_4 = np.random.randint(10, size=(3,3))

In [43]:
# Dot product - using transpose
np.dot(array_3.T, array_4)

array([[ 18,  91,  64],
       [ 48, 136, 108],
       [ 12,  74,  55]])

### Sorting arrays

In [45]:
# Sorting an array in ascending order
random_array = np.random.randint(10, size=(3, 5))
np.sort(random_array)

array([[0, 5, 6, 9, 9],
       [0, 1, 3, 4, 8],
       [5, 6, 7, 8, 9]])

In [46]:
# Sorting the indexes
np.argsort(random_array)

array([[1, 4, 3, 0, 2],
       [3, 1, 0, 4, 2],
       [2, 1, 3, 4, 0]])

In [47]:
# Getting the index with the maximum value
np.argmax(random_array)

0